project:
  type: website
  resources:
    - index.html

website:
  title: "The Path Integral"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: about.qmd
        text: About
      - href: articles/index.html   
        text: Articles

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true