project:
  type: website
  output-dir: docs
  resources:
    - index.html

website:
  title: "The Path Integral"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: articles/
        text: Articles
      - href: contact.html
        text: Contact

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    include-in-header: google-analytics.html